// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from "./client"
import { client } from "./client.gen"
import type {
    GetEventTaxonomyData,
    GetEventTaxonomyErrors,
    GetEventTaxonomyResponses,
    HeadEventsData,
    HeadEventsErrors,
    HeadEventsResponses,
    HeadEventTaxonomyData,
    HeadEventTaxonomyResponses,
    ListEventsData,
    ListEventsErrors,
    ListEventsResponses,
    OptionsEventsData,
    OptionsEventsResponses,
    OptionsEventTaxonomyData,
    OptionsEventTaxonomyResponses,
} from "./types.gen"

export type Options<
    TData extends TDataShape = TDataShape,
    ThrowOnError extends boolean = boolean,
    TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>
}

/**
 * Discover event types, category groups, and rooms
 *
 * Returns the currently published event taxonomy, including every event type nested under its category group and all room IDs. IDs match those used by the events feed. The response is localized to Norwegian by default.
 */
export const getEventTaxonomy = <ThrowOnError extends boolean = false>(
    options?: Options<GetEventTaxonomyData, ThrowOnError>,
) =>
    (options?.client ?? client).get<
        GetEventTaxonomyResponses,
        GetEventTaxonomyErrors,
        ThrowOnError
    >({ url: "/api/v1/events/taxonomy", ...options })

/**
 * Check the event taxonomy snapshot
 */
export const headEventTaxonomy = <ThrowOnError extends boolean = false>(
    options?: Options<HeadEventTaxonomyData, ThrowOnError>,
) =>
    (options?.client ?? client).head<HeadEventTaxonomyResponses, unknown, ThrowOnError>({
        url: "/api/v1/events/taxonomy",
        ...options,
    })

/**
 * Inspect taxonomy API CORS policy
 */
export const optionsEventTaxonomy = <ThrowOnError extends boolean = false>(
    options?: Options<OptionsEventTaxonomyData, ThrowOnError>,
) =>
    (options?.client ?? client).options<OptionsEventTaxonomyResponses, unknown, ThrowOnError>({
        url: "/api/v1/events/taxonomy",
        ...options,
    })

/**
 * List complete public event occurrences
 *
 * Returns every occurrence matching the inclusive date filters. Each occurrence includes the complete public event record, including a sanitized HTML/plain-text description and website, ticket, and Facebook links. Unknown query parameters return 400.
 */
export const listEvents = <ThrowOnError extends boolean = false>(
    options?: Options<ListEventsData, ThrowOnError>,
) =>
    (options?.client ?? client).get<ListEventsResponses, ListEventsErrors, ThrowOnError>({
        url: "/api/v1/events",
        ...options,
    })

/**
 * Check the public event snapshot
 *
 * Returns the same status, cache headers, and ETag as GET without a response body.
 */
export const headEvents = <ThrowOnError extends boolean = false>(
    options?: Options<HeadEventsData, ThrowOnError>,
) =>
    (options?.client ?? client).head<HeadEventsResponses, HeadEventsErrors, ThrowOnError>({
        url: "/api/v1/events",
        ...options,
    })

/**
 * Inspect event API CORS policy
 */
export const optionsEvents = <ThrowOnError extends boolean = false>(
    options?: Options<OptionsEventsData, ThrowOnError>,
) =>
    (options?.client ?? client).options<OptionsEventsResponses, unknown, ThrowOnError>({
        url: "/api/v1/events",
        ...options,
    })
