// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: "https://www.samfunnetibergen.no" | (string & {})
}

export type PublicEventsResponse = {
    data: Array<{
        id: string
        schedule:
            | {
                  /**
                   * The occurrence has a concrete start time.
                   */
                  kind: "timed"
                  /**
                   * UTC start timestamp in ISO 8601 format.
                   */
                  startsAt: string
                  /**
                   * UTC end timestamp, or null when the end is unknown.
                   */
                  endsAt: string | null
                  /**
                   * Local time zone used by the editorial schedule.
                   */
                  timeZone: "Europe/Oslo"
              }
            | {
                  /**
                   * The occurrence has no concrete time.
                   */
                  kind: "date"
                  /**
                   * Local calendar date in Europe/Oslo.
                   */
                  date: string
                  /**
                   * Local time zone used by the editorial schedule.
                   */
                  timeZone: "Europe/Oslo"
              }
        event: {
            id: string
            slug: string
            kind:
                | "single"
                | "seriesParent"
                | "seriesInstance"
                | "festivalParent"
                | "festivalSession"
            status: "scheduled" | "cancelled"
            updatedAt: string | null
            /**
             * Localized public event title.
             */
            title: string
            description: {
                /**
                 * Sanitized HTML description using the supported subset.
                 */
                html: string
                /**
                 * Plain-text description.
                 */
                text: string
            }
            image: {
                /**
                 * Absolute image URL.
                 */
                url: string
                /**
                 * Optional image caption.
                 */
                caption: string | null
            } | null
            eventType: {
                id: string
                name: string
            } | null
            taxonomyGroup: {
                id: string
                name: string
            } | null
            organizer:
                | {
                      kind: "group"
                      id: string
                      name: string
                      slug: string
                  }
                | {
                      kind: "text"
                      name: string
                  }
                | null
            location:
                | {
                      kind: "room"
                      id: string
                      name: string
                      slug: string
                      floor: number | null
                      imageUrl: string | null
                  }
                | {
                      kind: "text"
                      name: string
                  }
                | {
                      kind: "venue"
                      name: "Det Akademiske Kvarter"
                  }
            pricing: {
                currency: "NOK"
                isFree: boolean
                ordinary: number | null
                student: number | null
                member: number | null
            }
            parent: {
                id: string
                slug: string
                kind:
                    | "single"
                    | "seriesParent"
                    | "seriesInstance"
                    | "festivalParent"
                    | "festivalSession"
                status: "scheduled" | "cancelled"
                title: string
                /**
                 * Canonical website URL for the parent event.
                 */
                website: string
            } | null
            links: {
                /**
                 * Canonical website URL for this event.
                 */
                website: string
                /**
                 * Purchase URL, when available.
                 */
                ticket: string | null
                /**
                 * Facebook URL, when available.
                 */
                facebook: string | null
            }
        }
    }>
    meta: {
        locale: "nb" | "en"
        from: string
        to: string | null
    }
}

export type PublicErrorResponse = {
    error: {
        code: "invalid_request" | "internal_error"
        message: string
    }
}

export type ListEventsData = {
    body?: never
    headers?: {
        /**
         * ETag from an earlier response. A match returns 304 without a body.
         */
        "If-None-Match"?: string
    }
    path?: never
    query?: {
        /**
         * Localized response. Norwegian is the default and fallback locale.
         */
        locale?: "nb" | "en"
        /**
         * Inclusive local start date in Europe/Oslo. Defaults to today.
         */
        from?: string
        /**
         * Inclusive local end date in Europe/Oslo. Omit for no upper bound.
         */
        to?: string
    }
    url: "/api/v1/events"
}

export type ListEventsErrors = {
    /**
     * Invalid request
     */
    400: PublicErrorResponse
    /**
     * Temporary server failure
     */
    500: PublicErrorResponse
}

export type ListEventsError = ListEventsErrors[keyof ListEventsErrors]

export type ListEventsResponses = {
    /**
     * Public event occurrences
     */
    200: PublicEventsResponse
}

export type ListEventsResponse = ListEventsResponses[keyof ListEventsResponses]

export type HeadEventsData = {
    body?: never
    headers?: {
        /**
         * ETag from an earlier response. A match returns 304 without a body.
         */
        "If-None-Match"?: string
    }
    path?: never
    query?: {
        /**
         * Localized response. Norwegian is the default and fallback locale.
         */
        locale?: "nb" | "en"
        /**
         * Inclusive local start date in Europe/Oslo. Defaults to today.
         */
        from?: string
        /**
         * Inclusive local end date in Europe/Oslo. Omit for no upper bound.
         */
        to?: string
    }
    url: "/api/v1/events"
}

export type HeadEventsErrors = {
    /**
     * Invalid request
     */
    400: unknown
    /**
     * Temporary server failure
     */
    500: unknown
}

export type HeadEventsResponses = {
    /**
     * Snapshot is available
     */
    200: unknown
}

export type OptionsEventsData = {
    body?: never
    path?: never
    query?: never
    url: "/api/v1/events"
}

export type OptionsEventsResponses = {
    /**
     * CORS preflight accepted
     */
    204: void
}

export type OptionsEventsResponse = OptionsEventsResponses[keyof OptionsEventsResponses]
